version: "3"
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: otel-frontend
    ports:
      - 8081:8081
    environment:
      PORT: "8081"
      URL: "http://backend:8080"
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: otel-backend
    ports:
      - 8080:8080
    environment:
      DB_PASSWORD: "otel_password"
      DB_PORT: "5432"
      DB_USER: "app"
      DB_NAME: "otel"
      DB_HOST: "postgres"
      PORT: "8080"
    depends_on:
      - postgres
  postgres:
    image: postgres:16.2
    container_name: otel-database
    environment:
      POSTGRES_PASSWORD: "test123"
    volumes:
      - type: bind
        source: ./database/docker-entrypoint-initdb.d
        target: /docker-entrypoint-initdb.d
      - type: bind
        source: ./backend/db/schema
        target: /db/schema
    ports:
      - 5432:5432
